Error handling for AttributeCertificateIterator
google/authenticode-rs pull request #31
Opened 2023-09-23 15:30 UTC by N0fix

PR for issue #29 adding error handling for AttributeCertificateIterator.
Basically checks bounds for reads, and throws AttributeCertificateError::OutOfBounds when needed.

2023-09-24 18:03 UTC, nicholasbishop requested changes

2023-09-24 21:23 UTC, N0fix commented on authenticode/src/win_cert.rs
> +            u16::from_le_bytes(cert_bytes.get(6..8)?.try_into().unwrap());
I missed this line, indeed !

2023-09-24 22:10 UTC, N0fix commented on authenticode/src/win_cert.rs
> +        let cert_data_size = cert_size.checked_sub(header_size)?;
Added an enum member `InvalidCertificateSize` for this error, and switched `OutOfBonds` to `InvalidSize`, which seemed to be more appropriate from what I have read from the code.

2023-09-24 22:10 UTC, N0fix commented
Thanks for the reviews !

2023-09-26 16:39 UTC, nicholasbishop approved these changes
lgtm, thanks!

2023-09-26 16:47 UTC, merged